/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        AVLTree tree = new AVLTree();

        tree.insert(3);
        tree.insert(4);
        tree.insert(5);
        tree.insert(6);

        String serializedTree = tree.serialize(tree.root);
        System.out.println(serializedTree);

        tree.delete(4);
        serializedTree = tree.serialize(tree.root);
        System.out.println(serializedTree);

        AVLTree.Node root = tree.deserialize(serializedTree);

        tree.printTree(root);
    }
}
